bracketapp/routes/archive.py
from bracketapp.queries import bracket_queries
from flask import Blueprint, render_template, redirect, url_for
from bracketapp.utils import bracket_utils


archive_bp = Blueprint("archive_bp", __name__)


@archive_bp.get("/archive")
def archive():
    archived_years = bracket_queries.get_all_completed_correct_brackets()

    return render_template("archive.html", archived_years=archived_years)


@archive_bp.get("/archive/<int:year>")
def archive_year(year):
    standings, winners, correct = bracket_utils.get_bracket_standings_for_year(year)

    if len(standings) == 0:
        return redirect(url_for("viewbracket_bp.view_cbracket", year=correct.year))

    return render_template(
        "standings.html",
        content_url=url_for("archive_bp.api_archive_year", year=correct.year),
    )


@archive_bp.get("/api/archive/<int:year>")
def api_archive_year(year):
    # TODO: return the correct bracket if possible?
    # I forgot what I meant by this. Maybe bring correct to the
    # page to show correct winners on brackets table?
    standings, winners, correct = bracket_utils.get_bracket_standings_for_year(year)

    standings_dict = [correct.to_dict(include_games=False)] + [
        b.to_dict(safe_only=False, include_games=False) for b in standings
    ]
    winners_dict = [b.to_dict(safe_only=False, include_games=False) for b in winners]

    return dict(
        standings=standings_dict,
        winners=winners_dict,
        year=year,
    )

bracketapp/routes/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from bracketapp.queries import user_queries
from bracketapp.models import User
from bracketapp import bcrypt
from bracketapp.utils import send_email
import stream_chat
import os

auth_bp = Blueprint("auth_bp", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("leaderboard_bp.index"))

    email = request.args.get("email")
    if email:
        return render_template("login.html", email=email)

    email = request.form.get("email")
    password = request.form.get("password")
    remember = request.form.get("remember")

    if email and password:
        user = user_queries.get_user_by_email(email=email)

        if user and bcrypt.check_password_hash(user.password, password):
            remember = True if remember == "True" else False
            login_user(user, remember=remember)
            next_url = request.args.get("next")
            if not next_url:
                next_url = url_for("mybrackets_bp.my_brackets")
            return redirect(next_url)

        elif user:
            flash("Password was incorrect. Try again", "danger")
            return render_template("login.html", email=email)

        flash("User not found. Please create an acount", "neutral")

    return render_template("login.html", email=email)


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")

        if not user_queries.is_email_unique(email):
            flash("Email already exists. Please log in", "primary")
            return redirect(url_for("auth_bp.login", email=email))

        if not user_queries.is_username_unique(username):
            flash(
                "Username already exists. Please choose a different username",
                "danger",
            )
            return redirect(url_for("auth_bp.signup"))

        if len(password1) < 6:
            flash("Password must be longer than 6 characters. Try again", "warning")
            return redirect(url_for("auth_bp.signup"))

        user_queries.create_user(email=email, username=username, password=password1)

        try:
            send_email.send_signup_notification_email()
        except Exception:
            pass

        flash("Sign up succesful", "success")
        return redirect(url_for("auth_bp.login"))

    return render_template("signup.html")


@auth_bp.route("/password_request", methods=["GET", "POST"])
def password_request():
    if current_user.is_authenticated:
        user = user_queries.get_user_by_id(id=current_user.id)
        token = user.get_reset_token()
        return redirect(url_for("auth_bp.password_reset", token=token))

    if request.method == "POST":
        email = request.form.get("email")
        user = user_queries.get_user_by_email(email=email)
        send_email.send_reset_email(user)
        flash(
            "An email has been sent with instructions to reset your password. (Check spam folder)",
            "primary",
        )
        return redirect(url_for("auth_bp.login"))

    return render_template("password_request.html")


@auth_bp.route("/password_reset", methods=["GET", "POST"])
def password_reset():
    token = request.args.get("token")
    if request.method == "POST":
        user = User.verify_reset_token(token)
        if not user:
            flash("That is an invalid or expired token", "danger")
            if current_user.is_authenticated:
                return redirect(url_for("profile_bp.profile"))
            else:
                return redirect(url_for("auth_bp.password_request"))

        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        if password1 != password2:
            flash("Passwords are not equal. Please try again", "warning")
            return render_template("password_reset.html")

        user_queries.update_user_password(user.id, password=password1)
        flash(
            "Your password has been updated! You are now able to log in",
            "success",
        )
        return redirect(url_for("auth_bp.login"))

    return render_template("password_reset.html")


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth_bp.login"))


@auth_bp.route("/username_unique", methods=["GET"])
def username_unique():
    username = request.args.get("username")

    return {"isUnique": user_queries.is_username_unique(username)}


@auth_bp.route("/email_unique", methods=["GET"])
def email_unique():
    email = request.args.get("email")

    return {"isUnique": user_queries.is_email_unique(email)}


@auth_bp.get("/create_streamchat_token")
@login_required
def create_streamchat_token():
    server_client = stream_chat.StreamChat(
        api_key=os.environ.get("STREAM_CHAT_API_KEY"),
        api_secret=os.environ.get("STREAM_CHAT_SECRET_KEY"),
    )

    token = server_client.create_token(f"{current_user.id}")
    user_queries.update_user(id=current_user.id, token=token)

    return current_user.to_dict()

bracketapp/routes/deletebracket.py
from bracketapp.queries import bracket_queries, group_queries
from flask import Blueprint, redirect, url_for, flash
from flask_login import login_required
from bracketapp.config import CAN_EDIT_BRACKET, YEAR


deletebracket_bp = Blueprint("deletebracket_bp", __name__)


@deletebracket_bp.post("/delete_bracket/<int:id>")
@login_required
def delete_bracket(id):
    bracket = bracket_queries.get_my_bracket_for_bracket_id(bracket_id=id)
    if bracket and bracket.year == YEAR and CAN_EDIT_BRACKET:
        bracket_queries.delete_bracket(bracket_id=bracket.id)
        flash("Bracket deleted", "success")

    return redirect(url_for("mybrackets_bp.my_brackets"))


@deletebracket_bp.post("/delete_group_bracket/<int:id>")
@login_required
def delete_group_bracket(id):
    group_bracket = group_queries.get_my_group_bracket_for_id(group_bracket_id=id)
    if not group_bracket:
        return redirect(url_for("mybrackets_bp.my_brackets"))

    bracket = bracket_queries.get_my_bracket_for_bracket_id(
        bracket_id=group_bracket.bracket_id
    )
    if bracket and bracket.year == YEAR and CAN_EDIT_BRACKET:
        group_queries.delete_group_bracket(group_bracket_id=group_bracket.id)
        flash("Bracket Removed", "success")

    return redirect(url_for("mybrackets_bp.my_brackets"))

bracketapp/routes/editbracket.py
from bracketapp.queries import bracket_queries, group_queries
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required
from bracketapp.utils import bracket_utils
from bracketapp.config import CAN_EDIT_BRACKET


editbracket_bp = Blueprint("editbracket_bp", __name__)


@editbracket_bp.get("/edit_bracket/<int:id>")
@login_required
def edit_bracket(id):
    group_id = request.args.get("group_id")

    if not CAN_EDIT_BRACKET:
        # if we have a bracket id and we can't edit, go to viewing the bracket
        return redirect(url_for("viewbracket_bp.view_bracket", id=id))

    bracket = bracket_queries.get_my_bracket_for_bracket_id(bracket_id=id)

    if not bracket:
        # is this really what i want to do?
        return redirect(url_for("viewbracket_bp.view_bracket", id=id))

    if group_id and not group_queries.get_group_member(group_id=group_id):
        flash("You must join this group to submit a bracket", "danger")
        return redirect(url_for("groups_bp.view_group", id=group_id))

    default = bracket_queries.get_default_bracket()

    return render_template(
        "edit_bracket.html",
        bracket=bracket.to_dict(safe_only=False),
        default=default.to_dict(),
        group_id=group_id,
    )


@editbracket_bp.get("/new_bracket")
@login_required
def new_bracket():
    group_id = request.args.get("group_id")
    my_bracket_count = bracket_queries.my_bracket_count()
    if my_bracket_count >= 5:
        # if we don't have a bracket id and we are already at the max number of
        # # brackets, flash a message and go to viewing my brackets
        flash("You have already created 5/5 brackets for this year", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    if not CAN_EDIT_BRACKET:
        # if we don't have a bracket id and we can't edit, go to viewing my brackets
        flash("Editing is disabled", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    if group_id and not group_queries.get_group_member(group_id=group_id):
        flash("You must join this group to submit a bracket", "danger")
        return redirect(url_for("groups_bp.view_group", id=group_id))

    bracket = bracket_queries.get_empty_bracket()
    default = bracket_queries.get_default_bracket()

    return render_template(
        "edit_bracket.html",
        bracket=bracket.to_dict(safe_only=False),
        default=default.to_dict(),
        group_id=group_id,
    )


@editbracket_bp.post("/edit_bracket/<int:id>")
@login_required
def edit_bracket_post(id):
    group_id = request.args.get("group_id")

    if not CAN_EDIT_BRACKET:
        # if we have a bracket id and we can't edit, go to viewing the bracket
        return redirect(url_for("viewbracket_bp.view_bracket", id=id))

    if group_id and not group_queries.get_group_member(group_id=group_id):
        flash("You must join this group to submit a bracket", "danger")
        return redirect(url_for("groups_bp.view_group", id=group_id))

    existing_bracket = bracket_queries.update_bracket_from_form(id, request.form)

    if existing_bracket:
        flash("Bracket saved", "success")
        if group_id:
            return redirect(url_for("groups_bp.view_group", id=group_id))

    else:
        flash("No bracket was found for that id. Please try again", "danger")

    return redirect(url_for("mybrackets_bp.my_brackets"))


@editbracket_bp.post("/new_bracket")
@login_required
def new_bracket_post():
    group_id = request.args.get("group_id")
    my_bracket_count = bracket_queries.my_bracket_count()
    if my_bracket_count >= 5:
        # if we don't have a bracket id and we are already at the max number of
        # # brackets, flash a message and go to viewing my brackets
        flash("You have already created 5/5 brackets for this year", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    if not CAN_EDIT_BRACKET:
        # if we can't edit, go to viewing my brackets
        return redirect(url_for("mybrackets_bp.my_brackets"))

    if group_id and not group_queries.get_group_member(group_id=group_id):
        flash("You must join this group to submit a bracket", "danger")
        return redirect(url_for("groups_bp.view_group", id=group_id))

    new_bracket = bracket_queries.create_bracket_from_form(request.form)

    if group_id:
        group_queries.create_group_bracket(group_id=group_id, bracket_id=new_bracket.id)

        flash("Bracket saved", "success")
        return redirect(url_for("groups_bp.view_group", id=group_id))

    flash("Bracket saved", "success")
    return redirect(url_for("mybrackets_bp.my_brackets"))


@editbracket_bp.post("/bracket_join_group/<int:id>")
@login_required
def bracket_join_group(id):
    group_id = request.form.get("group_id")

    group = group_queries.get_group(group_id=group_id)
    if not group:
        flash("Sorry, this group could not be found", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    bracket = bracket_queries.get_my_bracket_for_bracket_id(bracket_id=id)
    if not bracket:
        flash("Sorry, this bracket could not be found", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    group_queries.create_group_bracket(group_id=group.id, bracket_id=bracket.id)

    flash(f"Your bracket has been added to {group.name}", "success")
    return redirect(url_for("groups_bp.view_group", id=group.id))


@editbracket_bp.post("/add_bracket_to_group/<int:id>")
@login_required
def add_bracket_to_group(id):
    bracket_id = request.form.get("bracket_id")

    bracket = bracket_queries.get_my_bracket_for_bracket_id(bracket_id=bracket_id)
    if not bracket:
        flash("Sorry, this bracket could not be found", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    group = group_queries.get_group(group_id=id)
    if not group:
        flash("Sorry, this group could not be found", "danger")
        return redirect(url_for("mybrackets_bp.my_brackets"))

    group_queries.create_group_bracket(group_id=group.id, bracket_id=bracket.id)

    flash(f"Your bracket has been added to {group.name}", "success")
    return redirect(url_for("groups_bp.view_group", id=group.id))

bracketapp/routes/mybrackets.py
from bracketapp.queries import bracket_queries, group_queries
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from bracketapp.utils import bracket_utils
from bracketapp.config import YEAR, CAN_EDIT_BRACKET
from bracketapp import app


mybrackets_bp = Blueprint("mybrackets_bp", __name__)


def is_admin():
    return (
        current_user.is_authenticated
        and current_user.role is not None
        and current_user.role > 1
    )


@mybrackets_bp.get("/my_brackets")
@login_required
def my_brackets():
    return render_template("my_brackets.html")


@mybrackets_bp.get("/api/my_brackets")
@login_required
def api_my_brackets():
    brackets = [
        b.to_dict(safe_only=False)
        for b in bracket_queries.get_all_my_brackets(
            sort=True, include_group_brackets=True
        )
    ]

    groups = [g.to_dict() for g in group_queries.get_all_groups_for_user(sort=True)]

    return dict(
        brackets=brackets,
        groups=groups,
        year=YEAR,
    )

bracketapp/routes/preferences.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from bracketapp.queries import theme_queries

preferences_bp = Blueprint("preferences_bp", __name__)


@preferences_bp.route("/preferences", methods=["GET"])
@login_required
def preferences():
    return render_template("preferences.html")


@preferences_bp.route("/set_primary_color", methods=["GET"])
@login_required
def set_primary_color():
    color = request.args.get("color")
    theme_queries.set_theme(color=color)
    return {"success": True}


@preferences_bp.route("/set_background_color", methods=["GET"])
@login_required
def set_background_color():
    background_color = request.args.get("backgroundColor")
    theme_queries.set_theme(background_color=background_color)
    return {"success": True}

bracketapp/routes/profile.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from bracketapp.queries import user_queries

profile_bp = Blueprint("profile_bp", __name__)


@profile_bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    user = user_queries.get_user_by_id(id=current_user.id)
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")

        user_queries.update_user(id=user.id, email=email, username=username)

        return redirect(url_for("profile_bp.profile"))
    return render_template("profile.html", username=user.username, email=user.email)

bracketapp/routes/theme.py
from flask import Blueprint, request
from flask_login import current_user
from bracketapp.queries import theme_queries


theme_bp = Blueprint("theme_bp", __name__)


@theme_bp.route("/set_theme", methods=["GET"])
def set_theme():
    if not current_user.is_authenticated:
        return {}

    theme = request.args.get("theme")
    theme = "light" if theme == "light" else "dark"
    theme_queries.set_theme(theme_color=theme)
    return {"success": True}

bracketapp/templates/base.html
<!DOCTYPE html>
<html
  lang="en"
  data-bs-theme="{{ theme }}"
  class="sl-theme-{{ theme }} {{ color }}-primary"
>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="NB Bracket Challenge. A site to create brackets for college hockey playoffs."
    />

    <link rel="manifest" href="/static/manifest.webmanifest" />

    <!-- Shoelace components -->
    <script
      type="module"
      src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.12.0/cdn/shoelace.js"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <!-- This is only for error monitoring -->
    <script
      src="https://js.sentry-cdn.com/d1913311367ec68822f82f8ced7bc88f.min.js"
      crossorigin="anonymous"
      defer
    >
      if (window.Sentry) {
            Sentry.onLoad(function () {
              Sentry.init({
                release: "nbbracketchallengefront@1.0.13",
                environment: "production",
                replaysSessionSampleRate: 0,
                replaysOnErrorSampleRate: 1.0,
              });
            });
          }
    </script>

    <link href="/static/css/output.css" rel="stylesheet" />
    <link href="/static/css/light.css" rel="stylesheet" />
    <link href="/static/css/dark.css" rel="stylesheet" />
    <link href="/static/css/themes.css" rel="stylesheet" />

    <link
      rel="icon"
      href="{% block icon %}/static/images/logo.svg{% endblock icon %}"
    />
    <title>{% block title %}{% endblock title %}</title>
    <script src="/static/js/nb-theme-selector.mjs" type="module"></script>
    <script src="/static/js/nb-login.mjs" type="module"></script>
    <script src="/static/js/nb-signup.mjs" type="module"></script>
    <script
      src="/static/js/nb-password-reset-request.mjs"
      type="module"
    ></script>
    <script src="/static/js/nb-reset-password.mjs" type="module"></script>
    <script src="/static/js/nb-profile.mjs" type="module"></script>
    <script src="/static/js/nb-countdown.mjs" type="module"></script>
  </head>

  <style>
    @font-face {
      font-family: Inter;
      src: url("/static/fonts/Inter-VariableFont_slnt,wght.ttf");
    }
  </style>

  <script>
    const LOGIN_URL = "{{ url_for('auth_bp.login') }}";
    const SINGUP_URL = "{{ url_for('auth_bp.signup') }}";
    const PASSWORD_RESET_REQUEST_URL = "{{ url_for('auth_bp.password_request') }}";
    const PROFILE_URL = "{{ url_for('profile_bp.profile') }}";
    const USERNAME_UNIQUE_URL = "{{ url_for('auth_bp.username_unique') }}";
    const EMAIL_UNIQUE_URL = "{{ url_for('auth_bp.email_unique') }}";
    const THEME_URL = "{{ url_for('theme_bp.set_theme') }}";
    const THEME = "{{ theme }}";
    const CAN_EDIT_BRACKET = "{{ CAN_EDIT_BRACKET }}" == "True";
    const MY_BRACKET_COUNT = {{ MY_BRACKET_COUNT }};
    const CURRENT_YEAR = {{ CURRENT_YEAR }};
    const CREATE_STREAMCHAT_TOKEN_URL = "{{ url_for('auth_bp.create_streamchat_token') }}";
    {% if current_user.is_authenticated %}
    const CURRENT_USER = {{ current_user.to_dict()|tojson }};
    {% else %}
    const CURRENT_USER = {};
    {% endif %}

    // redirect to next if user logged in and next exists
    if (CURRENT_USER.id) {
      let nextURL = window.localStorage.getItem("next");
      window.localStorage.removeItem("next");
      if (nextURL) {
        if (window.location.pathname !== nextURL) {
          window.location.href = nextURL;
        }
      }
    }
  </script>

  <body
    class="{% if not backgroundColorMatches %}{{ backgroundColor }}-background{% endif %}"
    {%
    if
    backgroundColorMatches
    %}style="background-color: {{ backgroundColor }}"
    {%
    endif
    %}
  >
    {% include "navbar.html" %}

    <div class="container my-4 h-100">
      {% with messages = get_flashed_messages(with_categories=true) %}
      <div id="alerts" class="container d-flex justify-content-center">
        {% if messages %} {% for category, message in messages %}
        <sl-alert variant="{{ category }}" duration="5000" open closable>
          {{ message }}
        </sl-alert>
        {% endfor %} {% endif %}
      </div>
      {% endwith %} {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

bracketapp/templates/edit_bracket.html
{% extends "base.html" %} {% block title %}My Bracket{% endblock title %} {%
block mybracket %}active{% endblock mybracket %} {% block content %}
<script>
  {% if bracket.id %}
  const BRACKET_FORM_URL = "{{ url_for('editbracket_bp.edit_bracket', id=bracket.id) }}";
  {% else %}
  const BRACKET_FORM_URL = "{{ url_for('editbracket_bp.new_bracket', group_id=group_id) }}";
  {% endif %}

  const CANCEL_BRACKET_URL = "{{ url_for('mybrackets_bp.my_brackets') }}";
  const STANDINGS_URL = "{{ url_for('mybrackets_bp.my_brackets') }}";
  const ARCHIVE_URL = "{{ url_for('archive_bp.archive') }}";
</script>

<nb-edit-bracket
  bracket='{{ bracket|tojson }}'
  default='{{ default|tojson }}'
></nb-edit-bracke>

<script type="module" src="/static/js/nb-edit-bracket.mjs"></script>

{% endblock content %}

bracketapp/templates/my_brackets.html
{% extends "base.html" %} {% block title %}My Brackets{% endblock title %} {%
block mybrackets %}active{% endblock mybrackets %} {% block content %}
<script src="https://cdn.jsdelivr.net/npm/ag-grid-community@31.0.3/dist/ag-grid-community.min.js"></script>
<script>
  const NEW_BRACKET_LINK = "{{ url_for('editbracket_bp.new_bracket') }}";
  const CREATE_GROUP_URL = "{{ url_for('groups_bp.create_group') }}";
  const SEARCH_URL = "{{ url_for('groups_bp.search_groups') }}";
  const DELETE_GROUP_BRACKET_URL =
    "{{ url_for('deletebracket_bp.delete_group_bracket', id=0) }}";
  const MY_BRACKETS_CONTENT_URL =
    "{{ url_for('mybrackets_bp.api_my_brackets') }}";
</script>
<link
  rel="preload"
  href="{{ url_for('mybrackets_bp.api_my_brackets') }}"
  as="fetch"
/>

<nb-my-brackets theme="{{ theme }}"></nb-my-brackets>

<nb-create-group></nb-create-group>

<script type="module" src="/static/js/nb-my-brackets.mjs"></script>
<script type="module" src="/static/js/nb-create-group.mjs"></script>

{% endblock content %}

bracketapp/templates/preferences.html
{% extends "base.html" %} {% block title %}Preferences{% endblock title %} {%
block preferences %}active{% endblock preferences %} {% block content %}
<script>
  const COLOR_URL = "{{ url_for('preferences_bp.set_primary_color') }}";
  const BACKGROUND_COLOR_URL =
    "{{ url_for('preferences_bp.set_background_color') }}";
</script>

<sl-card class="col-12 col-lg-7">
  <div class="d-flex flex-column gap-3">
    <h2>Customize</h2>

    <div>
      <h4>Theme</h4>
      <sl-radio-group
        id="preferences-theme-selector"
        label="Select a theme"
        value="{{ theme }}"
      >
        <sl-radio value="light">Light</sl-radio>
        <sl-radio value="dark">Dark</sl-radio>
      </sl-radio-group>
    </div>

    <sl-divider></sl-divider>

    <div>
      <h4>Background color</h4>
      <div class="row">
        <div class="col-6">
          <sl-radio-group
            id="preferences-background-color-selector"
            label="Select a background color"
            value="{{ backgroundColor }}"
          >
            <sl-radio value="">Default</sl-radio>
            <sl-radio value="custom">
              Custom
              <sl-color-picker
                id="colorPicker"
                format="hsl"
                opacity
                label="Select a color"
              ></sl-color-picker>
            </sl-radio>
            <sl-radio value="niks-favorite">Niklas' favorite</sl-radio>
            <sl-radio value="red">Red</sl-radio>
            <sl-radio value="gray">Gray</sl-radio>
            <sl-radio value="orange">Orange</sl-radio>
            <sl-radio value="amber">Amber</sl-radio>
            <sl-radio value="yellow">Yellow</sl-radio>
            <sl-radio value="lime">Lime</sl-radio>
            <sl-radio value="green">Green</sl-radio>
            <sl-radio value="emerald">Emerald</sl-radio>
            <sl-radio value="teal">Teal</sl-radio>
            <sl-radio value="cyan">Cyan</sl-radio>
            <sl-radio value="sky">Sky</sl-radio>
            <sl-radio value="blue">Blue</sl-radio>
            <sl-radio value="indigo">Indigo</sl-radio>
            <sl-radio value="violet">Violet</sl-radio>
            <sl-radio value="purple">Purple</sl-radio>
            <sl-radio value="fuchsia">Fuchsia</sl-radio>
            <sl-radio value="pink">Pink</sl-radio>
            <sl-radio value="rose">Rose</sl-radio>
          </sl-radio-group>
        </div>
        <div class="col-6">
          <label>Preview</label>
          <div
            class="background-preview {{ backgroundColor }}-background"
          ></div>
        </div>
      </div>
    </div>

    <sl-divider></sl-divider>

    <div>
      <h4>Color</h4>
      <div class="row">
        <div class="col-6">
          <sl-radio-group
            id="preferences-primary-color-selector"
            label="Select a primary color"
            value="{{ color }}"
          >
            <sl-radio value="">Default</sl-radio>
            <sl-radio value="red">Red</sl-radio>
            <sl-radio value="gray">Gray</sl-radio>
            <sl-radio value="orange">Orange</sl-radio>
            <sl-radio value="amber">Amber</sl-radio>
            <sl-radio value="yellow">Yellow</sl-radio>
            <sl-radio value="lime">Lime</sl-radio>
            <sl-radio value="green">Green</sl-radio>
            <sl-radio value="emerald">Emerald</sl-radio>
            <sl-radio value="teal">Teal</sl-radio>
            <sl-radio value="cyan">Cyan</sl-radio>
            <sl-radio value="sky">Sky</sl-radio>
            <sl-radio value="blue">Blue</sl-radio>
            <sl-radio value="indigo">Indigo</sl-radio>
            <sl-radio value="violet">Violet</sl-radio>
            <sl-radio value="purple">Purple</sl-radio>
            <sl-radio value="fuchsia">Fuchsia</sl-radio>
            <sl-radio value="pink">Pink</sl-radio>
            <sl-radio value="rose">Rose</sl-radio>
          </sl-radio-group>
        </div>
        <div class="col-6">
          <sl-button variant="primary">Preview</sl-button>
        </div>
      </div>
    </div>
  </div>
</sl-card>

<script src="/static/js/preferences.js"></script>
{% endblock content %}